<?php

namespace App\Dorcas\Hub\Enum;

class BanksNGClass
{
    const ABU_Microfinance_Bank  = '090197';
    const Abucoop_Microfinance_Bank = '090424';
    const Above_Only_Microfinance_Bank = '090260';
    const AA_FINANCE = '050005';
    const AG_Mortgage_Bank = '100028';
    const Adeyemi_College_Staff_Microfinance_Bank = '090268';
    const Ada_Microfinance_Bank = '090483';
    const Agosasa_Microfinance_Bank = '090371';
    const Afemai_Microfinance_Bank = '090518';
    const AL_Barakah_Microfinance_Bank = '090133';
    const Alpha_Kapital_Microfinance_Bank = '090169';
    const Al_Hayat_Microfinance_Bank = '090277';
    const Accion_Microfinance_Bank = '090134';
    const Apeks_Microfinance_Bank= '090143';
    const AMML_MFB = '090116';
    const Ampersand_Microfinance_Bank = '090529';
    const AMJU_Unique_Microfinance_Bank = '090180';
    const Anchorage_Microfinance_Bank = '090476';
    const Aniocha_Microfinance_Bank = '090469';
    const ABBEY_MORTGAGE_BANK = '070010';
    const Abulesoro_Microfinance_Bank_Ltd = '090545';
    const Akuchukwu_Microfinance_Bank_Ltd = '090561';
    const AB_Microfinance_Bank = '090270';
    const ACCESS_BANK = '044';
    const ACCESS_MONEY = '323'; 
    const ACCESS_MOBILE = '100013';
    const Accelerex_Network = '090202';
    const Addosser_Microfinance_Bank = '090160';
    const AFRIBANK = '014';
    const Afekhafe_Microfinance_Bank = '090292';
    const AKWA_SAVINGS_LOANS_LIMITED = '070025';
    const AMOYE_MICROFINANCE_BANK = '090610';
    const ku_Microfinance_Bank = '090531';
    const Allworkers_Microfinance_Bank= '090131';
    const Ally_Microfinance_Bank = '090548';
    const Alekun_Microfinance_Bank = '090259';
    const Alert_Microfinance_Bank = '090297';
    const Alvana_Microfinance = '090489';
    const Apple_Microfinance_Bank= '090376';
    const Amac_Microfinance_Bank = '090394';
    const Arise_Microfinance_Bank = '090282';
    const Aramoko_Microfinance_Bank = '090307';
    const Arca_Payments = '110011';
    const Assets_Microfinance_Bank = '090473';
    const Atbu_Microfinance_Bank = '090451';
    const Assets_Matrix_Microfinance_Bank = '090287';
    const Akpo_Microfinance_Bank = '090608';
    const ASO_SAVINGS_AND_LOANS = '401';
    const Astrapolaris_Microfinance_Bank = '090172';
    const Aspire_Microfinance_Bank_Ltd = '090544';
    const Avuenegbe_Microfinance_Bank = '090478';
    const Auchi_Microfinance_Bank = '090264';
    const AVE_MARIA_MICROFINANCE_BANK_LTD = '090600';
    const Aztec_Microfinance_Bank = '090540';
    const Balogun_Gambari_Microfinance_Bank = '090326';
    const Banex_Microfinance_Bank = '090425';
    const BRANCH = '050006';
    const Beststar_Microfinance_Bank = '090615';
    const Beta_Access_Yello = '100052';
    const Broadview_Microfinance_Bank_Ltd = '090568';
    const Balera_Microfinance_Bank_Ltd = '090563';
    const Benysta_Microfinance_Bank = '090413';
    const Bowen_Microfinance_Bank = '090148';
    const BRENT_MORTGAGE_BANK = '070015';
    const BANC_CORP_MICROFINANCE_BANK = '090581';
    const Balogun_Fulani_Microfinance_Bank = '090181';
    const Bayero_Microfinance_Bank  = '090316';
    const Bipc_Microfinance_Bank = '090336';
    const Bluewhales_Microfinance_Bank = '090431';
    const Blue_Investments_Microfinance_Bank = '090538';
    const Boctrust_Microfinance_Bank = '090117';
    const Bishopgate_Microfinance_Bank = '090555';
    const Boi_Mf_Bank = '090444';
    const Boji_Boji_Microfinance_Bank = '090494';
    const Borgu_Microfinance_Bank = '090395';
    const Bonghe_Microfinance_Bank = '090319';
    const Borstal_Microfinance_Bank = '090454';
    const Boromu_Microfinance_Bank = '090501';
    const Baobab_Microfinance_Bank = '090136';
    const Baines_Credit_Microfinance_Bank = '090188';
    const BC_Kash_Microfinance_Bank = '090127';
    const Bosak_Microfinance_Bank = '090176';
    const Borno_Renaissance_Microfinance_Bank = '090508';
    const Brethren_Microfinance_Bank = '090293';
    const BRIDGEWAY_MICROFINANCE_BANK = '090393';
    const Brightway_Microfinance_Bank  = '090308';
    const Business_Support_Microfinance_Bank = '090406';
    const Bud_Infrastructure_Limited = '110021';
    const Calabar_Microfinance_Bank = '090415';
    const Capricorn_Digital = '110023';
    const Caretaker_Microfinance_Bank = '090472';
    const Capstone_Mf_Bank = '090445';
    const Capitalmetriq_Swift_Microfinance_Bank = '090509';const Catland_Microfinance_Bank = '090498';
    const Cedar_Microfinance_Bank_Ltd = '090562';
    const CBN_TSA = '999001';
    const CITI_BANK  = '023';
    const CIT_Microfinance_Bank = '090144';
    const Citizen_Trust_Microfinance_Bank_Ltd = '090343';
    const CHAMS_MOBILE = '303';
    const Chanelle_Bank = '090397';
    const Cherish_Microfinance_Bank = '090440';
    const Chibueze_Microfinance_Bank = '090416';
    const Chukwunenye_Microfinance_Bank = '090490';
    const Cintrust_Microfinance_Bank = '090480';
    const Cloverleaf_Microfinance_Bank = '090511';
    const COOP_MORTGAGE_BANK = '070021';
    const Confidence_Microfinance_Bank_Ltd = '090530';
    const CONVENANT_MICROFINANCE_BANK = '551';
    const CORONATION_MERCHANT_BANK = '559';
    const COUNTY_FINANCE_LTD = '050001';
    const CELLULANT = '317';
    const Cellulant_Pssp = '110012';
    const Coalcamp_Microfinance_Bank = '090254';
    const Coastline_Microfinance_Bank = '090374';
    const Consistent_Trust_Microfinance_Bank_Ltd = '090553';
    const Corestep_Microfinance_Bank = '090365';
    const CENTRAL_BANK_OF_NIGERIA = '000028';
    const CEMCS_Microfinance_Bank = '090154';
    const Contec_Global_Infotech_Limited = '100032';
    const Cashconnect_Microfinance_Bank = '090360';
    const Consumer_Microfinance_Bank = '090130';
    const Chikum_Microfinance_Bank = '090141';
    const Chase_Microfinance_Bank = '090523';
    const Credit_Afrique_Microfinance_Bank = '090159';
    const Crutech_Microfinance_Bank = '090414';
    const Crowdforce = '110017';
    const Crescent_Microfinance_Bank = '090526';
    const Creditville_Microfinance_Bank = '090611';
    const Crossriver_Microfinance_Bank = '090429';
    const Cyberspace_Limited = '110014';
    const DELTA_TRUST_MORTGAGE_BANK = '070023';
    const DIAMOND_BANK = '063';
    const DIGNITY_FINANCE = '050013';
    const DOT_MICROFINANCE_BANK = '090470';
    const Davodani_Microfinance_Bank = '090391';
    const Daylight_Microfinance_Bank = '090167';
    const Esan_Microfinance_Bank = '090189';
    const Ebsu_Microfinance_Bank = '090427';
    const EARTHOLEUM = '302';
    const E_Barcs_Microfinance_Bank = '090156';
    const ECOBANK = '050';
    const EKONDO_MFB = '090097';
    const ECOBANK_MOBILE = '090097';
    const EcoMobile = '100030';
    const Ecobank_Xpress_Account = '100008';
    const Emeralds_Microfinance_Bank = '090273';
    const Evergreen_Microfinance_Bank = '090332';
    const Eagle_Flight_Microfinance_Bank = '090294';
    const Edfin_Microfinance_Bank = '090310';
    const Egwafin_Microfinance_Bank_Ltd = '090556';
    const ENTERPRISE_BANK = '084';
    const Enrich_Microfinance_Bank = '090539';
    const Ek_Reliable_Microfinance_Bank = '090389';
    const Ekimogun_Microfinance_Bank = '090552';
    const ETRANZACT = '306';
    const ENAIRA = '000033';
    const ENCO_FINANCE = '050012';
    const EsoE_Microfinance_Bank = '090166';
    const Excellent_Microfinance_Bank = '090541';
    const Empire_Trust_MFB = '090114';
    const Eyowo_MFB = '090328';
    const Evangel_Microfinance_Bank = '090304';
    const Ewt_Microfinance_Bank = '090572';
    const FAST_CREDIT = '050009';
    const Fairmoney_Microfinance_Bank_Ltd = '090551';
    const FEDETH_MICROFINANCE_BANK = '090482';
    const Fame_Microfinance_Bank = '090330';
    const Federal_Polytechnic_Nekede_Microfinance_Bank = '090398';
    const FBN_MORTGAGE_LIMITED = '090107';
    const FIRST_BANK_MOBILE = '309';
    const FIRST_BANK = '011';
    const FIRST_GENERATION_MORTGAGE_BANK = '070014';
    const First_Multiple_Microfinance_Bank = '090163';
    const First_Royal_Microfinance_Bank = '090164';
    const First_Option_Microfinance_Bank = '090285';
    const First_Heritage_Microfinance_Bank = '090479';
    const FINATRUST_MICROFINANCE_BANK = '608';
    const FORTIS_MOBILE = '308';
    const FORTIS_MICROFINANCE_BANK = '501';
    const Fortress_Microfinance_Bank = '090486';
    const FIDELITY_BANK = '070';
    const FIDELITY_MOBILE = '318';
    const Firstmidas_Microfinance_Bank_Ltd = '090575';
    const Fidfund_Microfinance_Bank = '090126';
    const Firmus_MFB = '090366';
    const First_Apple_Limited = '110004';
    const Fims_Microfinance_Bank = '090507';
    const FCMB = '214';
    const FCMB_Easy_Account = '100031';
    const Fcmb_Microfinance_Bank = '090409';
    const FSDH = '601';
    const FSDH_Merchant_Bank  = '400001';
    const FHA_MORTGAGE_BANK_LTD = '070026';
    const FET = '314';
    const Foresight_Microfinance_Bank = '090521';
    const Federalpoly_Nasarawamfb = '090298';
    const Federal_University_Dutse_Microfinance_Bank = '090318';
    const Finca_Microfinance_Bank = '090400';
    const Fct_Microfinance_Bank = '090290';
    const FFS_Microfinance_Bank = '090153';
    const FLOURISH_MFB = '090614';
    const Flutterwave_Technology_Solutions_Limited = '110002';
    const Futminna_Microfinance_Bank = '090438';
    const Fullrange_Microfinance_Bank = '090145';
    const Futo_Microfinance_Bank = '090158';
    const FEWCHORE_FINANCE_COMPANY_LTD = '050002';
    const FUNDQUEST_FINANCIAL_SERVICES_LTD = '050010';
    const FBNQUEST_MERCHANT_BANK = '060002';
    const FAST_Microfinance_Bank = '090179';
    const GATEWAY_MORTGAGE_BANK = '070009';
    const GoMoney = '100022';
    const Gbede_Microfinance_Bank = '090579';
    const GOLDMAN_MICROFINANCE_BANK = '090574';
    const Garki_Microfinance_Bank = '090484';
    const Giant_Stride_Microfinance_Bank = '090475';
    const Good_Neighbours_Microfinance_Bank = '090467';
    const Giginya_Microfinance_Bank = '090411';
    const Gmb_Microfinance_Bank = '090408';
    const Gashua_Microfinance_Bank = '090168';
    const Glory_Microfinance_Bank = '090278';
    const Gabsyn_Microfinance_Bank = '090591';
    const GIDAUNIYAR_ALHERI_MICROFINANCE_BANK = '090621';
    const GOMBE_MICROFINANCE_BANK_LTD = '090586';
    const GOODNEWS_MFB = '090495';
    const Gti_Microfinance_Bank = '090385';
    const GTBANK = '058';
    const GTBANK_MOBILE_MONEY = '315';
    const GTMobile = '100009';
    const GLOBUS_BANK = '103';
    const Greenacres_MFB= '090599';
    const Gowans_Microfinance_Bank = '090122';
    const Gwong_Microfinance_Bank = '090500';
    const Grant_MF_Bank  = '090335';
    const GREENWICH_MERCHANT_BANK = '060004';
    const GreenBank_Microfinance_Bank = '090178';
    const Green_Energy_Microfinance_Bank_Ltd = '090550';
    const Greenville_Microfinance_Bank = '090269';
    const Giwa_Microfinance_Bank = '090441';
    const Girei_Microfinance_Bank = '090186';
    const Grooming_Microfinance_Bank = '090195';
    const Halacredit_Microfinance_Bank = '090291';
    const HERITAGE_BANK = '030';
    const Highland_Microfinance_Bank = '090418';
    const Hopepsb = '120002';
    const HEDONMARK = '324';
    const Headway_Microfinance_Bank = '090363';
    const HAGGAI_MORTGAGE_BANK = '070017';
    const HOMEBASE_MORTGAGE = '070024';
    const Hasal_Microfinance_Bank = '090121';
    const Hackman_Microfinance_Bank = '090147';
    const IMPERIAL_HOMES_MORTGAGE_BANK = '415';
    const INFINITY_TRUST_MORTGAGE_BANK = '070016';
    const Intellifin = '100027';
    const Iwade_Microfinance_Bank_Ltd = '090578';
    const Interland_Microfinance_Bank = '090386';
    const Interswitch_Financial_Inclusion_Services = '110010';
    const Infinity_Microfinance_Bank = '090157';
    const Innovectives_Kesh = '100029';
    const IBILE_Microfinance_Bank = '090118';
    const IBA_MFB = '090598';
    const Interswitch_Limited = '110003';
    const Ibeto_Microfinance_Bank = '090439';
    const Ibu_Aje_Microfinance = '090488';
    const Ibolo_Micorfinance_Bank_Ltd = '090532';
    const Ijebu_Ife_Microfinance_Bank_Ltd = '090546';
    const Ibom_Fadama_Microfinance_Bank = '090519';
    const Ic_Globalmicrofinance_Bank = '090520';
    const Itex_Integrated_Services_Limited = '090211';
    const Illorin_Microfinance_Bank = '090350';
    const Ilora_Microfinance_Bank = '090430';
    const Ilasan_Microfinance_Bank = '090370';
    const IRL_Microfinance_Bank = '090149232';
    const Imo_State_Microfinance_Bank = '090258';
    const Insight_Microfinance_Bank = '090434';
    const Imowo_Microfinance_Bank = '090417';
    const Iperu_Microfinance_Bank = '090493';
    const Ikire_Microfinance_Bank = '090279';
    const Ikenne_Microfinance_Bank = '090324';
    const Ikoyi_Osun_Microfinance_Bank = '090536';
    const Isaleoyo_Microfinance_Bank = '090377';
    const Isuofia_Microfinance_Bank = '090353';
    const Ishie_Microfinance_Bank = '090428';
    const Iwoama_Microfinance_Bank = '090543';
    const Iyeru_Okin_Microfinance_Bank_Ltd = '090337';
    const Iyamoye_Microfinance_Bank_Ltd = '090570';
    const Ilaro_Poly_Microfinance_Bank_Ltd = '090571';
    const Izon_Microfinance_Bank = '090421';
    const Iyin_Ekiti_MFB = '090620';
    const ISLAND_MICROFINANCE_BANK = '090584';
    const JAIZ_BANK = '301';
    const JUBILEE_LIFE_MORTGAGE_BANK = '402';
    const Jessefield_Microfinance_Bank = '090352';
    const KENECHUKWU_MICROFINANCE_BANK = '090602';
    const KEYSTONE_BANK = '082';
    const Kegow = '100015';
    const Kegow_Chamsmobile = '100036';
    const Kadpoly_Microfinance_Bank = '090320';
    const Kayvee_Microfinance_Bank = '090554';
    const Kadick_Integration_Limited = '110008';
    const Kc_Microfinance_Bank = '090549';
    const Kingdom_College_Microfinance_Bank = '090487';
    const Kuda = '090267';
    const Kwasu_Mf_Bank = '090450';
    const Koraypay = '110022';
    const Kontagora_Microfinance_Bank = '090299';
    const KCMB_Microfinance_Bank = '090191';
    const KKU_Microfinance_Bank = '090606';
    const KANO_POLY_MFB = '090592';
    const Kredi_Money_Microfinance_Bank = '090380';
    const LOTUS_BANK = '000029';
    const Lovonus_Microfinance_Bank = '090265';
    const LAGOS_BUILDING_INVESTMENT_COMPANY = '070012';
    const Legend_Microfinance_Bank = '090372';
    const Letshego_MFB = '090420';
    const Leadremit_Limited = '110044';
    const La_Fayette_Microfinance_Bank = '090155';
    const Lapo_Microfinance_Bank = '090177';
    const Landgold_Microfinance_Bank = '090422';
    const Lavender_Microfinance_Bank = '090271';
    const Links_Microfinance_Bank = '090435';
    const Lifegate_Microfinance_Bank_Ltd = '090557';
    const Light_Microfinance_Bank = '090477';
    const Lobrem_Microfinance_Bank = '090537';
    const Mainland_Microfinance_Bank = '090323';
    const Malachy_Microfinance_Bank = '090174';
    const Megapraise_Microfinance_Bank = '090280';
    const Macrod_MFB = '090603';
    const Mainstreet_Microfinance_Bank = '090171';
    const Mercury_MFB = '090589';
    const Medef_Microfinance_Bank = '090612';
    const MAUTECH_Microfinance_Bank = '090423';
    const Manny_Microfinance_bank = '090383';
    const Maritime_Microfinance_Bank = '090410';
    const MAYFRESH_MORTGAGE_BANK = '070019';
    const Memphis_Microfinance_Bank = '090432';
    const Meridian_Microfinance_Bank= '090275';
    const Microvis_Microfinance_Bank = '090113';
    const MINT_FINEX_MICROFINANCE_BANK = '090281';
    const Money_Master_Psb = '120005';
    const Mgbidi_Microfinance_Bank = '090528';
    const Midland_Microfinance_Bank = '090192';
    const Microsystems_Investment_And_Development_Limited = '110018';
    const Mab_Allianz_MFB = '090623';
    const MKUDI = '313';
    const Mayfair_Microfinance_Bank = '090321';
    const Maintrust_Microfinance_Bank = '090465';
    const Momo_Psb = '120003';
    const Monarch_Microfinance_Bank = '090462';
    const Moyofade_Mf_Bank = '090448';
    const MKOBO_MICROFINANCE_BANK_LTD = '090455';
    const M36 = '100035';
    const Microbiz_Microfinance_Bank = '090587';
    const Money_Trust_Microfinance_Bank = '090129';
    const Mozfin_Microfinance_Bank = '090392';
    const Molusi_Microfinance_Bank = '090362';
    const Moniepoint_Microfinance_Bank = '090405';
    const Mutual_Trust_Microfinance_Bank = '090151';
    const Mutual_Benefits_Microfinance_Bank = '090190';
    const Navy_Microfinance_Bank = '090263';
    const NEWEDGE_FINANCE_LTD  = '050004';
    const NIRSAL_Microfinance_Bank  = '090194';
    const Nice_Microfinance_Bank = '090459';
    const NEW_PRUDENTIAL_BANK = '090108';
    const New_Dawn_Microfinance_Bank = '090205';
    const New_Golden_Pastures_Microfinance_Bank = '090378';
    const Nwannegadi_Microfinance_Bank = '090399';
    const Neptune_Microfinance_Bank = '090329';
    const Netapps_Technology_Limited = '110025';
    const Nkpolu_Ust_Microfinance = '090535';
    const NIP_VIRTUAL_BANK = '999';
    const Nigeria_Prisonsmicrofinance_Bank = '090505';
    const Nibssussd_Payments = '110019';
    const NPF_MICROFINANCE_BANK = '552';
    const NOVA_MERCHANT_BANK = '060003';
    const Nomba_Financial_Services_Limited = '110028';
    const Ndiorah_Microfinance_Bank= '090128';
    const Nagarta_Microfinance_Bank = '090152';
    const Nasarawa_Microfinance_Bank = '090349';
    const Nsuk_Microfinance_Bank = '090491';
    const Numo_Microfinance_Bank = '090516';
    const Nuture_Microfinance_Bank = '090364';
    const OMOLUABI_MORTGAGE_BANK = '990';
    const OPTIMUS_BANK = '000036';
    const One_Finance = '100026';
    const Orisun_MFB = '090588';
    const Octopus_Microfinance_Bank_Ltd = '090576';
    const Oke_Aro_Oredegbe_Microfinance_Bank_Ltd = '090565';
    const Okuku_Microfinance_Bank_Ltd = '090566';
    const Orokam_Microfinance_Bank_Ltd = '090567';
    const Oluyole_Microfinance_Bank = '090460';
    const Okpoga_Microfinance_Bank = '090161';
    const Olowolagba_Microfinance_Bank = '090404';
    const Oakland_Microfinance_Bank = '090437';
    const Oau_Microfinance_Bank_Ltd = '090345';
    const Ohafia_Microfinance_Bank = '090119';
    const Olabisi_Onabanjo_University_Microfinance_Bank = '090272';
    const Olofin_Owena_Microfinance_Bank = '090468';
    const Ojokoro_Microfinance_Bank = '090527';
    const Oluchukwu_Microfinance_Bank = '090471';
    const Otuo_Microfinance_Bank_Ltd = '090542';
    const Oraukwu_Microfinance_Bank = '090492';
    const Ospoly_Microfinance_Bank = '232';
    const Omiye_Microfinance_Bank= '090456';
    const Oche_Microfinance_Bank = '090333';
    const Oscotech_Microfinance_Bank = '090396';
    const Otech_Microfinance_Bank_Ltd = '090580';
    const Opay = '100004';
    const ProvidusBank_PLC = '101';
    const PAGE_MFBank = '560';
    const PAGE_FINANCIALS = '070008';
    const PAGATECH = '327';
    const PARKWAY = '311';
    const Parkway_Mf_Bank = '090390';
    const Parkway_ReadyCash = '100003';
    const PAYCOM = '305';
    const PALMPAY = '100033';
    const Paystack_Payments_Limited = '110006';
    const PAYATTITUDE_ONLINE = '329';
    const Projects_Microfinance_Bank = '090503';
    const PARRALEX = '526';
    const PARALLEX_BANK = '000030';
    const Palmcoast_Microfinance_Bank = '090497';
    const PARRALEX_MICROFINANCE_BANK = '090004';
    const PatrickGold_Microfinance_Bank = '090317';
    const Peace_Microfinance_Bank = '090402';
    const Peniel_Micorfinance_Bank_Ltd = '090379';
    const Personal_Trust_Microfinance_Bank = '090135';
    const PecanTrust_Microfinance_Bank = '090137';
    const Pennywise_Microfinance_Bank = '090196';
    const Petra_Microfinance_Bank = '090165';
    const Pillar_Microfinance_Bank = '090289';
    const PLATINUM_MORTGAGE_BANK = '070013';
    const POLARIS_BANK = '076';
    const Polyibadan_Microfinance_Bank = '090534';
    const Polyuwanna_Microfinance_Bank = '090296';
    const PREMIUM_TRUST_BANK = '000031';
    const Prisco_Microfinance_Bank = '090481';
    const Pristine_Divitis_Microfinance_Bank = '090499';
    const Preeminent_Microfinance_Bank = '090412';
    const Prestige_Microfinance_Bank = '090274';
    const Purplemoney_Microfinance_Bank = '090303';
    const Quickfund_Microfinance_Bank = '090261';
    const Qr_Payments = '110013';
    const Qube_Microfinance_Bank_Ltd = '090569';
    const Radalpha_Microfinance_Bank = '090496';
    const REFUGE_MORTGAGE_BANK = '070011';
    const Rigo_Microfinance_Bank = '090433';
    const Rima_Microfinance_Bank = '090443';
    const Resident_Fintech_Limited = '110024';
    const Rehoboth_Microfinance_Bank = '090463';
    const Rand_merchant_Bank = '502';
    const Regent_Microfinance_Bank = '090125';
    const RenMoney_Microfinance_Bank = '090198';
    const Reliance_Microfinance_Bank = '090173';
    const Royal_Exchange_Microfinance_Bank = '090138';
    const Rockshield_Microfinance_Bank = '090547';
    const Rahama_Microfinance_Bank = '090170';
    const Richway_Microfinance_Bank = '090132';
    const Rephidim_Microfinance_Bank = '090322';
    const RAYYAN_Microfinance_Bank = '090616';
    const SAFETRUST_MORTGAGE_BANK = '403';
    const Seed_Capital_Microfinance_Bank = '090112';
    const Seedvest_Microfinance_Bank = '090369';
    const SIGNATURE_BANK = '000034';
    const SKYE_BANK = '076';
    const Support_Mf_Bank = '090446';
    const Shepherd_Trust_Microfinance_Bank = '090401';
    const Shongom_Microfinance_Bank_Ltd = '090558';
    const Smartcash_Payment_Service_Bank = '120004';
    const Sparkle = '090325';
    const Spay_Business = '110026';
    const Seap_Microfinance_Bank = '090513';
    const Spectrum_Microfinance_Bank = '090436';
    const Solid_Allianze_Microfinance_Bank = '090506';
    const Solidrock_Microfinance_Bank = '090524';
    const Supreme_Microfinance_Bank_Ltd = '090564';
    const Snow_Microfinance_Bank = '090573';
    const Stanbic_IBTC_Ease_Wallet = '100007';
    const STATESIDE_MFB = '090583';
    const STANBIC_IBTC = '221';
    const STANBIC_MOBILE_MONEY = '304';
    const STB_MORTGAGE_BANK = '070022';
    const STANDARD_CHARTERED_BANK = '068';
    const Stanford_Microfinance_Bank = '090162';
    const Standard_Microfinance_Bank = '090182';
    const STERLING_BANK = '232';
    const Stellas_Microfinance_Bank= '090262';
    const STERLING_MOBILE = '326';
    const Stockcorp_Microfinance_Bank = '090340';
    const SUNTRUST_BANK = '100';
    const SAGEGREY_FINANCE_LIMITED = '050003';
    const Shalom_Microfinance_Bank = '090502';
    const SIMPLE_FINANCE_LIMITED = '050008';
    const SAFETRUST = '090006';
    const Safegate_Microfinance_Bank = '090485';
    const Safe_Haven_MFB = '090286';
    const Sagamu_Microfinance_Bank= '090140';
    const Sls_Mf_Bank = '090449';
    const Sunbeam_Microfinance_Bank = '090302';
    const Sulsap_Microfinance_Bank = '090305';
    const TAGPAY ='328';
    const Total_Trust_Microfinance_Bank = '090613';
    const Triple_A_Microfinance_Bank = '090524';
    const Tangerine_Bank = '090426';
    const TeamApt = '110007';
    const TEASYMOBILE ='319';
    const TEKLA_FINANCE_LTD  = '050007';
    const TRUSTBOND = '523';
    const TRUSTBOND_MORTGAGE_BANK = '090005';
    const TANADI_MFB = '090560';
    const Trustfund_Microfinance_Bank = '090276';
    const TCF_MFB = '90115';
    const Tf_Microfinance_Bank = '090373';
    const TEST_BANK = '090175';
    const TASUED_MICROFINANCE_BANK_LTD = '090593';
    const TITAN_TRUST_BANK = '000025';
    const Titan_Paystack = '100039';
    const TAJ_BANK_LIMITED = '000026';
    const TAJWALLET = '080002';
    const Thrive_Microfinance_Bank = '090283';
    const TRINITY_FINANCIAL_SERVICES_LIMITED = '050014';
    const Trident_Microfinance_Bank= '090146';
    const UBA = '033';
    const U_And_C_Microfinance_Bank = '090315';
    const Unaab_Microfinance_Bank = '090331';
    const UNION_BANK = '032';
    const UNITY_BANK = '215';
    const Uniibadan_Microfinance_Bank = '090461';
    const UNN_MFB = '090251';
    const Ummah_Microfinance_Bank = '090609';
    const Uda_Microfinance_Bank = '090403';
    const Unical_Microfinance_Bank = '090193';
    const Uniuyo_Microfinance_Bank = '090338';
    const Unilag_Microfinance_Bank = '090452';
    const Unimaid_Microfinance_Bank = '090464';
    const Unilorin_Microfinance_Bank = '090341';
    const Uniben_Microfinance_Bank = '090266';
    const Umunnachi_Microfinance_Bank = '090510';
    const Umuchinemere_Procredit_Microfinance_Bank = '090514';
    const Uhuru_Microfinance_Bank = '090517';
    const Uzondu_Mf_Bank = '090453';
    const Vas2Nets_Limited = '110015';
    const Venture_Garden_Nigeria_Limited = '110009';
    const Verdant_Microfinance_Bank = '090474';
    const VTNETWORKS = '320';
    const VFD_Micro_Finance_Bank = '090110';
    const Verite_Microfinance_Bank = '090123';
    const Visa_Microfinance_Bank = '090139';
    const Virtue_Microfinance_Bank = '090150';
    const WEMA_BANK = '035';
    const WAYA_MICROFINANCE_BANK_LTD = '090590';
    const Wetland_Microfinance_Bank = '090120';
    const Winview_Bank = '090419';
    const Woven_Financ = '110029';
    const Xslnce_Microfinance_Bank = '090124';
    const Xpress_Payments = '090201';
    const Yes_Microfinance_Bank = '090142';
    const Yct_Microfinance_Bank = '090466';
    const Yello_Digital_Financial_Services = '110027';
    const Yobe_Microfinance_Bank = '090252';
    const ZENITH_BANK = '057';
    const ZENITH_MOBILE = '322';
    const Zwallet = '100034';
    const Zikora_Microfinance_Bank = '090504';
    const Zinternet_Nigera_Limited = '100025';
    const 3Line_Card_Management_Limited = '110005';
    const 9Payment_Service_Bank = '120001';


    const BANK_CODES = [
        self::ABU_Microfinance_Bank  => 'ABU Microfinance Bank',
        self::Abucoop_Microfinance_Bank => 'Abucoop  Microfinance Bank',
        self::Above_Only_Microfinance_Bank => 'Above Only Microfinance Bank',
        self::AA_FINANCE              => 'Aaa Finance',
        self::AG_Mortgage_Bank => 'AG Mortgage Bank',
        self::Adeyemi_College_Staff_Microfinance_Bank  => 'Adeyemi College Staff Microfinance Bank',
        self::Ada_Microfinance_Bank => 'Ada Microfinance Bank',
        self::Agosasa_Microfinance_Bank  => 'Agosasa Microfinance Bank',
        self::Afemai_Microfinance_Bank => 'Afemai Microfinance Bank',
        self::AL_Barakah_Microfinance_Bank => 'AL-Barakah Microfinance Bank',
        self::Alpha_Kapital_Microfinance_Bank => 'Alpha Kapital Microfinance Bank',
        self::Al_Hayat_Microfinance_Bank => 'Al-Hayat Microfinance Bank',
        self::Accion_Microfinance_Bank => 'Accion Microfinance Bank',
        self::Apeks_Microfinance_Bank=> 'Apeks Microfinance Bank',
        self::AMML_MFB                => 'AMML MFB',
        self::Ampersand_Microfinance_Bank => 'Ampersand Microfinance Bank',
        self::AMJU_Unique_Microfinance_Bank => 'AMJU Unique Microfinance Bank',
        self::Anchorage_Microfinance_Bank=> 'Anchorage Microfinance Bank',
        self::Aniocha_Microfinance_Bank => 'Aniocha Microfinance Bank',
        self::ABBEY_MORTGAGE_BANK     => 'Abbey Mortgage Bank',
        self::Abulesoro_Microfinance_Bank_Ltd  => 'Abulesoro Microfinance Bank Ltd',
        self::Akuchukwu_Microfinance_Bank_Ltd => 'Akuchukwu Microfinance Bank Ltd',
        self::AB_Microfinance_Bank  => 'AB Microfinance Bank',
        self::ACCESS_BANK             => 'Access Bank Nigeria',
        self::ACCESS_MONEY            => 'Access Money',
        self::Addosser_Microfinance_Bank => 'Addosser Microfinance Bank',
        self::ACCESS_MOBILE           => 'Access Mobile',
        self::Accelerex_Network  => 'Accelerex Network',
        self::AFRIBANK                => 'Afribank Nigeria Plc',
        self::Afekhafe_Microfinance_Bank => 'Afekhafe Microfinance Bank',
        self::AKWA_SAVINGS_LOANS_LIMITED => 'Akwa Savings & Loans Limited',
        self::AMOYE_MICROFINANCE_BANK => 'AMOYE MICROFINANCE BANK',
        self::Allworkers_Microfinance_Bank => 'Allworkers Microfinance Bank',
        self::Ally_Microfinance_Bank => 'Ally Microfinance Bank',
        self::Alekun_Microfinance_Bank  => 'Alekun Microfinance Bank',
        self::Alert_Microfinance_Bank => 'Alert Microfinance Bank',
        self::Alvana_Microfinance => 'Alvana Microfinance',
        self::Aku_Microfinance_Bank => 'Aku Microfinance Bank',
        self::Apple_Microfinance_Bank => 'Apple  Microfinance Bank',
        self::Amac_Microfinance_Bank => 'Amac Microfinance Bank',
        self::Arise_Microfinance_Bank => 'Arise Microfinance Bank',
        self::Aramoko_Microfinance_Bank => 'Aramoko Microfinance Bank',
        self::Arca_Payments => 'Arca Payments',
        self::Assets_Microfinance_Bank => 'Assets Microfinance Bank',
        self::Atbu_Microfinance_Bank => 'Atbu  Microfinance Bank',
        self::Assets_Matrix_Microfinance_Bank => 'Assets Matrix Microfinance Bank',
        self::Akpo_Microfinance_Bank  => 'Akpo Microfinance Bank',
        self::ASO_SAVINGS_AND_LOANS   => 'Aso Savings And Loans',
        self::Astrapolaris_Microfinance_Bank => 'Astrapolaris Microfinance Bank',
        self::Aspire_Microfinance_Bank_Ltd => 'Aspire Microfinance Bank Ltd',
        self::Avuenegbe_Microfinance_Bank => 'Avuenegbe Microfinance Bank',
        self::Auchi_Microfinance_Bank => 'Auchi Microfinance Bank',
        self::AVE_MARIA_MICROFINANCE_BANK_LTD => 'AVE MARIA MICROFINANCE BANK LTD',
        self::Aztec_Microfinance_Bank => 'Aztec Microfinance Bank',
        self::Banex_Microfinance_Bank  => 'Banex Microfinance Bank',
        self::BRANCH   => 'Branch International Financial Services',
        self::Beststar_Microfinance_Bank => 'Beststar Microfinance Bank',
        self::Beta_Access_Yello => 'Beta-Access Yello',
        self::Broadview_Microfinance_Bank_Ltd => 'Broadview Microfinance Bank Ltd',
        self::Balera_Microfinance_Bank_Ltd => 'Balera Microfinance Bank Ltd',
        self::Benysta_Microfinance_Bank => 'Benysta Microfinance Bank',
        self::Balogun_Gambari_Microfinance_Bank => 'Balogun Gambari Microfinance Bank',
        self::Bowen_Microfinance_Bank => 'Bowen Microfinance Bank',
        self::BRENT_MORTGAGE_BANK     => 'Brent Mortgage Bank',
        self::BANC_CORP_MICROFINANCE_BANK => 'BANC CORP MICROFINANCE BANK',
        self::Balogun_Fulani_Microfinance_Bank => 'Balogun Fulani  Microfinance Bank',
        self::Bayero_Microfinance_Bank => 'Bayero Microfinance Bank',
        self::Bipc_Microfinance_Bank => 'Bipc Microfinance Bank',
        self::Bluewhales_Microfinance_Bank => 'Bluewhales  Microfinance Bank',
        self::Blue_Investments_Microfinance_Bank                => 'Blue Investments Microfinance Bank',
        self::Boctrust_Microfinance_Bank => 'Boctrust Microfinance Bank',
        self::Bishopgate_Microfinance_Bank => 'Bishopgate Microfinance Bank',
        self::Boi_Mf_Bank => 'Boi Mf Bank',
        self::Boji_Boji_Microfinance_Bank => 'Boji Boji Microfinance Bank',
        self::Borgu_Microfinance_Bank => 'Borgu Microfinance Bank',
        self::Borstal_Microfinance_Bank => 'Borstal Microfinance Bank',
        self::Boromu_Microfinance_Bank => 'Boromu Microfinance Bank',
        self::Bonghe_Microfinance_Bank => 'Bonghe Microfinance Bank',
        self::Baobab_Microfinance_Bank=> 'Baobab Microfinance Bank',
        self::Baines_Credit_Microfinance_Bank => 'Baines Credit Microfinance Bank',
        self::BC_Kash_Microfinance_Bank => 'BC Kash Microfinance Bank',
        self::Bosak_Microfinance_Bank => 'Bosak Microfinance Bank',
        self::Borno_Renaissance_Microfinance_Bank => 'Borno Renaissance Microfinance Bank',
        self::Brethren_Microfinance_Bank => 'Brethren Microfinance Bank',
        self::BRIDGEWAY_MICROFINANCE_BANK => 'BRIDGEWAY MICROFINANCE BANK',
        self::Brightway_Microfinance_Bank => 'Brightway Microfinance Bank',
        self::Business_Support_Microfinance_Bank => 'Business Support Microfinance Bank',
        self::Bubayero_Microfinance_Bank => 'Bubayero Microfinance Bank',
        self::Bud_Infrastructure_Limited => 'Bud Infrastructure Limited',
        self::Calabar_Microfinance_Bank => 'Calabar Microfinance Bank',
        self::Capricorn_Digital => 'Capricorn Digital',
        self::Caretaker_Microfinance_Bank => 'Caretaker Microfinance Bank',
        self::Capstone_Mf_Bank => 'Capstone Mf Bank',
        self::Capitalmetriq_Swift_Microfinance_Bank => 'Capitalmetriq Swift Microfinance Bank',
        self::Catland_Microfinance_Bank => 'Catland Microfinance Bank',
        self::Cedar_Microfinance_Bank_Ltd=> 'Cedar Microfinance Bank Ltd',
        self::CBN_TSA => 'CBN_TSA',
        self::CITI_BANK               => 'Citi Bank',
        self::CIT_Microfinance_Bank => 'CIT Microfinance Bank',
        self::Citizen_Trust_Microfinance_Bank_Ltd => 'Citizen Trust Microfinance Bank Ltd',
        self::CHAMS_MOBILE            => 'Chams Mobile',
        self::Chanelle_Bank  => 'Chanelle Bank',
        self::Cherish_Microfinance_Bank => 'Cherish Microfinance Bank',
        self::Chibueze_Microfinance_Bank => 'Chibueze Microfinance Bank',
        self::Chukwunenye_Microfinance_Bank => 'Chukwunenye  Microfinance Bank',
        self::Cintrust_Microfinance_Bank => 'Cintrust Microfinance Bank',
        self::Cloverleaf_Microfinance_Bank => 'Cloverleaf  Microfinance Bank',
        self::COOP_MORTGAGE_BANK      => 'Coop Mortgage Bank',
        self::Confidence_Microfinance_Bank_Ltd => 'Confidence Microfinance Bank Ltd',
        self::CONVENANT_MICROFINANCE_BANK => 'Covenant Microfinance Bank',
        self::CORONATION_MERCHANT_BANK=> 'Coronation Merchant Bank',
        self::COUNTY_FINANCE_LTD      => 'County Finance Ltd',
        self::CELLULANT               => 'Cellulant',
        self::Cellulant_Pssp => 'Cellulant Pssp',
        self::Coalcamp_Microfinance_Bank => 'Coalcamp Microfinance Bank',
        self::Coastline_Microfinance_Bank => 'Coastline Microfinance Bank',
        self::Consistent_Trust_Microfinance_Bank_Ltd  => 'Consistent Trust Microfinance Bank Ltd',
        self::Corestep_Microfinance_Bank => 'Corestep Microfinance Bank', 
        self::CENTRAL_BANK_OF_NIGERIA => 'Central Bank Of Nigeria',
        self::CEMCS_Microfinance_Bank=> 'CEMCS Microfinance Bank',
        self::Contec_Global_Infotech_Limited => 'Contec Global Infotech Limited (NowNow)',
        self::Consumer_Microfinance_Bank  => 'Consumer Microfinance Bank',
        self::Cashconnect_Microfinance_Bank => 'Cashconnect Microfinance Bank',
        self::Chikum_Microfinance_Bank=> 'Chikum Microfinance Bank',
        self::Chase_Microfinance_Bank => 'Chase Microfinance Bank',
        self::Credit_Afrique_Microfinance_Bank  => 'Credit Afrique Microfinance Bank',
        self::Crutech_Microfinance_Bank => 'Crutech  Microfinance Bank',
        self::Crowdforce => 'Crowdforce',
        self::Crescent_Microfinance_Bank => 'Crescent Microfinance Bank',
        self::Creditville_Microfinance_Bank => 'Creditville Microfinance Bank',
        self::Crossriver_Microfinance_Bank => 'Crossriver  Microfinance Bank',
        self::Cyberspace_Limited => 'Cyberspace Limited',
        self::DELTA_TRUST_MORTGAGE_BANK => 'Delta Trust Mortgage Bank',
        self::DIAMOND_BANK            => 'Diamond Bank Plc (Access Bank)',
        self::DIGNITY_FINANCE         => 'Dignity Finance',
        self::DOT_MICROFINANCE_BANK => 'DOT MICROFINANCE BANK',
        self::Davodani_Microfinance_Bank => 'Davodani  Microfinance Bank',
        self::Daylight_Microfinance_Bank  => 'Daylight Microfinance Bank',
        self::Esan_Microfinance_Bank => 'Esan Microfinance Bank',
        self::Ebsu_Microfinance_Bank => 'Ebsu Microfinance Bank',
        self::EARTHOLEUM              => 'Eartholeum',
        self::E_Barcs_Microfinance_Bank=> 'E-Barcs Microfinance Bank',
        self::EKONDO_MFB         => 'Ekondo MFB',
        self::ECOBANK                 => 'Ecobank Nigeria Plc',
        self::ECOBANK_MOBILE          => 'Ecobank Mobile',
        self::EcoMobile => 'EcoMobile',
        self::Ecobank_Xpress_Account => 'Ecobank Xpress Account',
        self::Emeralds_Microfinance_Bank => 'Emeralds Microfinance Bank',
        self::Evergreen_Microfinance_Bank => 'Evergreen Microfinance Bank',
        self::Eagle_Flight_Microfinance_Bank => 'Eagle Flight Microfinance Bank',
        self::Edfin_Microfinance_Bank => 'Edfin Microfinance Bank',       
        self::Egwafin_Microfinance_Bank_Ltd => 'Egwafin Microfinance Bank Ltd',
        self::ENTERPRISE_BANK         => 'Enterprise Bank Limited',
        self::Enrich_Microfinance_Bank => 'Enrich Microfinance Bank',
        self::Ek_Reliable_Microfinance_Bank => 'Ek-Reliable Microfinance Bank',
        self::Ekimogun_Microfinance_Bank => 'Ekimogun Microfinance Bank',
        self::ETRANZACT               => 'ETranzact',
        self::ENAIRA                  => 'ENaira',
        self::ENCO_FINANCE            => 'Enco Finance',
        self::EsoE_Microfinance_Bank => 'Eso-E Microfinance Bank',
        self::Excellent_Microfinance_Bank => 'Excellent Microfinance Bank',
        self::Empire_Trust_MFB        => 'Empire Trust MFB',
        self::Eyowo_MFB                => 'Eyowo MFB',
        self::Evangel_Microfinance_Bank => 'Evangel Microfinance Bank',
        self::Ewt_Microfinance_Bank=> 'Ewt Microfinance Bank',
        self::FAST_CREDIT             => 'Fast Credit',
        self::FEDETH_MICROFINANCE_BANK => 'FEDETH MICROFINANCE BANK',
        self::Fame_Microfinance_Bank => 'Fame Microfinance Bank',
        self::FBN_MORTGAGE_LIMITED  => 'FBN Mortgages Limited',
        self::FAST_Microfinance_Bank => 'FAST Microfinance Bank',
        self::Fairmoney_Microfinance_Bank_Ltd => 'Fairmoney Microfinance Bank Ltd',
        self::Federal_Polytechnic_Nekede_Microfinance_Bank => 'Federal Polytechnic Nekede Microfinance Bank',
        self::Finca_Microfinance_Bank  => 'Finca Microfinance Bank',
        self::FIRST_BANK_MOBILE       => 'Fbn Mobile',
        self::FIRST_BANK              => 'First Bank Plc',
        self::FIRST_GENERATION_MORTGAGE_BANK => 'First Generation Mortgage Bank',
        self::First_Multiple_Microfinance_Bank => 'First Multiple Microfinance Bank',
        self::First_Royal_Microfinance_Bank => 'First Royal Microfinance Bank',
        self::First_Option_Microfinance_Bank  => 'First Option Microfinance Bank',
        self::First_Heritage_Microfinance_Bank => 'First Heritage Microfinance Bank',
        self::FINATRUST_MICROFINANCE_BANK=> 'FINATRUST MICROFINANCE BANK',
        self::FORTIS_MOBILE           => 'Fortis Mobile',
        self::FORTIS_MICROFINANCE_BANK=> 'Fortis Microfinance Bank',
        self::Fortress_Microfinance_Bank => 'Fortress Microfinance Bank',
        self::FIDELITY_BANK           => 'Fidelity Bank Plc',
        self::FIDELITY_MOBILE         => 'Fidelity Mobile',
        self::Firstmidas_Microfinance_Bank_Ltd => 'Firstmidas Microfinance Bank Ltd',
        self::Fidfund_Microfinance_Bank => 'Fidfund Microfinance Bank',
        self::Firmus_MFB => 'Firmus MFB',
        self::First_Apple_Limited => 'First Apple Limited',
        self::Fims_Microfinance_Bank => 'Fims Microfinance Bank',
        self::FCMB                    => 'First City Monument Bank Plc',
        self::FCMB_Easy_Account => 'FCMB Easy Account',
        self::Fcmb_Microfinance_Bank => 'Fcmb Microfinance Bank',
        self::FSDH_Merchant_Bank => 'FSDH Merchant Bank',
        self::FSDH                    => 'FSDH',
        self::FHA_MORTGAGE_BANK_LTD   => 'Fha Mortgage Bank Ltd',
        self::FET                     => 'FET',
        self::Foresight_Microfinance_Bank => 'Foresight Microfinance Bank',
        self::Federalpoly_Nasarawamfb => 'Federalpoly Nasarawamfb',
        self::Federal_University_Dutse_Microfinance_Bank  => 'Federal University Dutse Microfinance Bank',
        self::Fct_Microfinance_Bank => 'Fct Microfinance Bank',
        self::FFS_Microfinance_Bank  => 'FFS Microfinance Bank',
        self::FLOURISH_MFB                => 'FLOURISH MFB',
        self::Flutterwave_Technology_Solutions_Limited => 'Flutterwave Technology Solutions Limited',
        self::Futminna_Microfinance_Bank => 'Futminna Microfinance Bank',
        self::Fullrange_Microfinance_Bank => 'Fullrange Microfinance Bank',
        self::Futo_Microfinance_Bank=> 'Futo Microfinance Bank',
        self::FEWCHORE_FINANCE_COMPANY_LTD =>'Fewchore Finance Company Limited',
        self::FUNDQUEST_FINANCIAL_SERVICES_LTD => 'Fundquest Financial Services Ltd',
        self::FBNQUEST_MERCHANT_BANK  => 'FBNQUEST Merchant Bank',
        self::GATEWAY_MORTGAGE_BANK   => 'Gateway Mortgage Bank',
        self::GoMoney => 'GoMoney',
        self::Gbede_Microfinance_Bank => 'Gbede Microfinance Bank',
        self::GOLDMAN_MICROFINANCE_BANK => 'GOLDMAN MICROFINANCE BANK',
        self::Garki_Microfinance_Bank => 'Garki Microfinance Bank',
        self::Giant_Stride_Microfinance_Bank=> 'Giant Stride Microfinance Bank',
        self::Good_Neighbours_Microfinance_Bank => 'Good Neighbours Microfinance Bank',
        self::Giginya_Microfinance_Bank => 'Giginya Microfinance Bank',
        self::Giwa_Microfinance_Bank => 'Giwa Microfinance Bank',
        self::MONEYBOX                => 'Moneybox',
        self::Gmb_Microfinance_Bank  => 'Gmb Microfinance Bank',
        self::Gashua_Microfinance_Bank => 'Gashua Microfinance Bank',
        self::Glory_Microfinance_Bank => 'Glory Microfinance Bank',
        self::Gti_Microfinance_Bank => 'Gti  Microfinance Bank',
        self::Gabsyn_Microfinance_Bank => 'Gabsyn Microfinance Bank',
        self::GIDAUNIYAR_ALHERI_MICROFINANCE_BANK => 'GIDAUNIYAR ALHERI MICROFINANCE BANK',
        self::GOMBE_MICROFINANCE_BANK_LTD => 'GOMBE MICROFINANCE BANK LTD',
        self::GOODNEWS_MFB => 'GOODNEWS MFB',
        self::GTBANK                  => 'Gtbank Plc',
        self::GTBANK_MOBILE_MONEY     => 'Gtbank Mobile Money',
        self::GTMobile => 'GTMobile',
        self::GLOBUS_BANK             => 'Globus Bank',
        self::Greenacres_MFB => 'Greenacres MFB',
        self::Gowans_Microfinance_Bank => 'Gowans Microfinance Bank',
        self::Gwong_Microfinance_Bank => 'Gwong Microfinance Bank',
        self::Grant_MF_Bank => 'Grant MF Bank',
        self::GREENWICH_MERCHANT_BANK => 'Greenwich Merchant Bank',
        self::GreenBank_Microfinance_Bank => 'GreenBank Microfinance Bank',
        self::Green_Energy_Microfinance_Bank_Ltd => 'Green Energy Microfinance Bank Ltd',
        self::Greenville_Microfinance_Bank => 'Greenville Microfinance Bank',
        self::Girei_Microfinance_Bank => 'Girei Microfinance Bank',
        self::Grooming_Microfinance_Bank  => 'Grooming Microfinance Bank',
        self::Halacredit_Microfinance_Bank => 'Halacredit Microfinance Bank',
        self::HEDONMARK               => 'Hedonmark',
        self::Headway_Microfinance_Bank=> 'Headway Microfinance Bank',
        self::HERITAGE_BANK           => 'Heritage Bank',
        self::Highland_Microfinance_Bank  => 'Highland Microfinance Bank',
        self::Hopepsb => 'Hopepsb',
        self::HAGGAI_MORTGAGE_BANK    => 'Haggai Mortgage Bank Limited',
        self::HOMEBASE_MORTGAGE       => 'Homebase Mortgage',
        self::Hasal_Microfinance_Bank => 'Hasal Microfinance Bank',
        self::Hackman_Microfinance_Bank => 'Hackman Microfinance Bank',
        self::IMPERIAL_HOMES_MORTGAGE_BANK => 'Imperial Homes Mortgage Bank',
        self::INFINITY_TRUST_MORTGAGE_BANK => 'Infinity Trust Mortgage Bank',
        self::Intellifin => 'Intellifin',
        self::Iwade_Microfinance_Bank_Ltd => 'Iwade Microfinance Bank Ltd',
        self::Interland_Microfinance_Bank => 'Interland Microfinance Bank',
        self::Interswitch_Financial_Inclusion_Services => 'Interswitch Financial Inclusion Services (Ifis)',
        self::Infinity_Microfinance_Bank => 'Infinity Microfinance Bank',
        self::Innovectives_Kesh => 'Innovectives Kesh',
        self::IBILE_Microfinance_Bank  => 'IBILE Microfinance Bank',
        self::IBA_MFB => 'IBA MFB',
        self::Interswitch_Limited  => 'Interswitch Limited',
        self::Ibeto_Microfinance_Bank => 'Ibeto Microfinance Bank',
        self::Ijebu_Ife_Microfinance_Bank_Ltd => 'Ijebu_Ife_Microfinance_Bank_Ltd',
        self::Ibu_Aje_Microfinance => 'bu-Aje Microfinance',
        self::Ibolo_Micorfinance_Bank_Ltd => 'Ibolo Micorfinance Bank Ltd',
        self::Ibom_Fadama_Microfinance_Bank => 'Ibom Fadama Microfinance Bank',
        self::Ic_Globalmicrofinance_Bank => 'Ic Globalmicrofinance Bank',
        self::Itex_Integrated_Services_Limited => 'Itex Integrated Services Limited',
        self::Illorin_Microfinance_Bank=> 'Illorin Microfinance Bank',
        self::Ilora_Microfinance_Bank => 'Ilora Microfinance Bank',
        self::Ilasan_Microfinance_Bank => 'Ilasan Microfinance Bank',
        self::IRL_Microfinance_Bank=> 'IRL Microfinance Bank',
        self::Imo_State_Microfinance_Bank => 'Imo State Microfinance Bank',
        self::Iperu_Microfinance_Bank=> 'Iperu Microfinance Bank',
        self::Insight_Microfinance_Bank => 'Insight Microfinance Bank',
        self::Imowo_Microfinance_Bank => 'Imowo Microfinance Bank',
        self::Ikire_Microfinance_Bank => 'Ikire Microfinance Bank',
        self::Ikenne_Microfinance_Bank => 'Ikenne Microfinance Bank',
        self::Ikoyi_Osun_Microfinance_Bank => 'Ikoyi-Osun Microfinance Bank',
        self::Isaleoyo_Microfinance_Bank => 'Isaleoyo Microfinance Bank',
        self::Isuofia_Microfinance_Bank=> 'Isuofia Microfinance Bank',
        self::Ishie_Microfinance_Bank => 'Ishie  Microfinance Bank',
        self::Iwoama_Microfinance_Bank => 'Iwoama Microfinance Bank',
        self::Iyeru_Okin_Microfinance_Bank_Ltd => 'Iyeru Okin Microfinance Bank Ltd',
        self::Iyamoye_Microfinance_Bank_Ltd => 'Iyamoye Microfinance Bank Ltd',
        self::Ilaro_Poly_Microfinance_Bank_Ltd => 'Ilaro Poly Microfinance Bank Ltd',
        self::Izon_Microfinance_Bank => 'Izon Microfinance Bank',
        self::Iyin_Ekiti_MFB => 'Iyin Ekiti MFB',
        self::ISLAND_MICROFINANCE_BANK  => 'ISLAND MICROFINANCE BANK ',
        self::JAIZ_BANK  => 'Jaiz Bank',
        self::JUBILEE_LIFE_MORTGAGE_BANK => 'Jubilee Life Mortgage Bank',
        self::Jessefield_Microfinance_Bank=> 'Jessefield Microfinance Bank',
        self::KENECHUKWU_MICROFINANCE_BANK => 'KENECHUKWU MICROFINANCE BANK',
        self::KEYSTONE_BANK           => 'Keystone Bank Plc',
        self::Kegow => 'Kegow',
        self::Kegow_Chamsmobile => 'Kegow(Chamsmobile)',
        self::Kadpoly_Microfinance_Bank => 'Kadpoly Microfinance Bank',
        self::Kayvee_Microfinance_Bank => 'Kayvee Microfinance Bank',
        self::Kadick_Integration_Limited => 'Kadick Integration Limited',
        self::Kc_Microfinance_Bank => 'Kc Microfinance Bank',
        self::Kingdom_College_Microfinance_Bank => 'Kingdom College  Microfinance Bank',
        self::Kontagora_Microfinance_Bank => 'Kontagora Microfinance Bank',
        self::Kuda  => 'Kuda',
        self::Kwasu_Mf_Bank => 'Kwasu Mf Bank',
        self::Koraypay => 'Koraypay',
        self::KKU_Microfinance_Bank => 'KKU Microfinance Bank',
        self::KANO_POLY_MFB => 'KANO POLY MFB',
        self::KCMB_Microfinance_Bank => 'KCMB Microfinance Bank',
        self::Kredi_Money_Microfinance_Bank => 'Kredi Money Microfinance Bank',
        self::LOTUS_BANK              => 'Lotus Bank',
        self::Lovonus_Microfinance_Bank => 'Lovonus Microfinance Bank"',
        self::LAGOS_BUILDING_INVESTMENT_COMPANY => 'Lagos Building Investment Company',
        self::Legend_Microfinance_Bank => 'Legend Microfinance Bank',
        self::Letshego_MFB => 'Letshego MFB',
        self::Leadremit_Limited => 'Leadremit Limited',
        self::La_Fayette_Microfinance_Bank  => 'La Fayette Microfinance Bank',
        self::Lapo_Microfinance_Bank => 'Lapo Microfinance Bank',
        self::Landgold_Microfinance_Bank => 'Landgold  Microfinance Bank',
        self::Lavender_Microfinance_Bank  => 'Lavender Microfinance Bank',
        self::Links_Microfinance_Bank => 'Links Microfinance Bank',
        self::Lifegate_Microfinance_Bank_Ltd => 'Lifegate Microfinance Bank Ltd',
        self::Light_Microfinance_Bank => 'Light Microfinance Bank',
        self::Lobrem_Microfinance_Bank => 'Lobrem Microfinance Bank',
        self::Mainland_Microfinance_Bank => 'Mainland Microfinance Bank',
        self::Mercury_MFB => 'Mercury MFB',
        self::Medef_Microfinance_Bank => 'Medef Microfinance Bank',
        self::MAUTECH_Microfinance_Bank => 'MAUTECH Microfinance Bank',
        self::Manny_Microfinance_bank => 'Manny Microfinance bank',
        self::Maritime_Microfinance_Bank => 'Maritime Microfinance Bank',
        self::Malachy_Microfinance_Bank => 'Malachy Microfinance Bank',
        self::Megapraise_Microfinance_Bank => 'Megapraise Microfinance Bank',
        self::Macrod_MFB => 'Macrod MFB',
        self::MAYFRESH_MORTGAGE_BANK  => 'Mayfresh Mortgage Bank',
        self::Memphis_Microfinance_Bank => 'Memphis Microfinance Bank',
        self::Meridian_Microfinance_Bank => 'Meridian Microfinance Bank',
        self::Microvis_Microfinance_Bank                => 'Microvis Microfinance Bank',
        self::MINT_FINEX_MICROFINANCE_BANK => 'Mint-Finex MICROFINANCE BANK',
        self::Money_Master_Psb  => 'Money Master Psb',
        self::Mgbidi_Microfinance_Bank => 'Mgbidi Microfinance Bank',
        self::Midland_Microfinance_Bank => 'Midland Microfinance Bank',
        self::Microsystems_Investment_And_Development_Limited => 'Microsystems Investment And Development Limited',
        self::Mab_Allianz_MFB => 'Mab Allianz MFB',
        self::MKUDI                   => 'Mkudi',
        self::Mayfair_Microfinance_Bank => 'Mayfair  Microfinance Bank',
        self::Maintrust_Microfinance_Bank => 'Maintrust Microfinance Bank',
        self::Momo_Psb => 'Momo Psb',
        self::Monarch_Microfinance_Bank => 'Monarch Microfinance Bank',
        self::Moyofade_Mf_Bank => 'Moyofade Mf Bank',
        self::Microbiz_Microfinance_Bank => 'Microbiz Microfinance Bank',
        self::MKOBO_MICROFINANCE_BANK_LTD => 'MKOBO MICROFINANCE BANK LTD',
        self::M36  => 'M36',
        self::Money_Trust_Microfinance_Bank=> 'Money Trust Microfinance Bank',
        self::Mozfin_Microfinance_Bank => 'Mozfin Microfinance Bank',
        self::Molusi_Microfinance_Bank => 'Molusi Microfinance Bank',
        self::Moniepoint_Microfinance_Bank => 'Moniepoint Microfinance Bank',
        self::Mutual_Trust_Microfinance_Bank => 'Mutual Trust Microfinance Bank',
        self::Mutual_Benefits_Microfinance_Bank => 'Mutual Benefits Microfinance Bank',
        self::Navy_Microfinance_Bank => 'Navy Microfinance Bank',
        self::NEWEDGE_FINANCE_LTD     => 'Newedge Finance Ltd',
        self::NIRSAL_Microfinance_Bank  => 'NIRSAL Microfinance Bank',
        self::Nice_Microfinance_Bank => 'Nice Microfinance Bank',
        self::NEW_PRUDENTIAL_BANK                => 'New Prudential Bank',
        self::New_Dawn_Microfinance_Bank => 'New Dawn Microfinance Bank',
        self::New_Golden_Pastures_Microfinance_Bank => 'New Golden Pastures Microfinance Bank',
        self::Nwannegadi_Microfinance_Bank => 'Nwannegadi Microfinance Bank',
        self::Neptune_Microfinance_Bank => 'Neptune Microfinance Bank',
        self::Netapps_Technology_Limited => 'Netapps Technology Limited',
        self::Nkpolu_Ust_Microfinance => 'Nkpolu-Ust Microfinance',
        self::NIP_VIRTUAL_BANK        => 'NIP Virtual Bank',
        self::Nigeria_Prisonsmicrofinance_Bank => 'Nigeria Prisonsmicrofinance Bank',
        self::Nibssussd_Payments => 'Nibssussd Payments',
        self::NPF_MICROFINANCE_BANK   => 'NPF MicroFinance Bank',
        self::NOVA_MERCHANT_BANK      => 'Nova Merchant Bank',
        self::Nomba_Financial_Services_Limited => 'Nomba Financial Services Limited',
        self::Ndiorah_Microfinance_Bank => 'Ndiorah Microfinance Bank',
        self::Nagarta_Microfinance_Bank => 'Nagarta Microfinance Bank',
        self::Nasarawa_Microfinance_Bank => 'Nasarawa Microfinance Bank',
        self::Nsuk_Microfinance_Bank => 'Nsuk  Microfinance Bank',
        self::Nuture_Microfinance_Bank => 'Nuture Microfinance Bank',
        self::Numo_Microfinance_Bank => 'Numo Microfinance Bank',
        self::OMOLUABI_MORTGAGE_BANK  => 'Omoluabi Mortgage Bank',
        self::OPTIMUS_BANK            => 'Optimus Bank',
        self::One_Finance => 'One Finance',
        self::Orisun_MFB => 'Orisun MFB',
        self::Octopus_Microfinance_Bank_Ltd => 'Octopus Microfinance Bank Ltd',
        self::Oke_Aro_Oredegbe_Microfinance_Bank_Ltd => 'Oke_Aro Oredegbe Microfinance Bank Ltd',
        self::Okuku_Microfinance_Bank_Ltd=> 'Okuku Microfinance Bank Ltd',
        self::Orokam_Microfinance_Bank_Ltd => 'Orokam Microfinance Bank Ltd',
        self::Oluyole_Microfinance_Bank => 'Oluyole Microfinance Bank',
        self::Okpoga_Microfinance_Bank => 'Okpoga Microfinance Bank',
        self::Olowolagba_Microfinance_Bank => 'Olowolagba Microfinance Bank',
        self::Oakland_Microfinance_Bank => 'Oakland Microfinance Bank',
        self::Oau_Microfinance_Bank_Ltd=> 'Oau Microfinance Bank Ltd',
        self::Ohafia_Microfinance_Bank    => 'Ohafia Microfinance Bank',
        self::Olabisi_Onabanjo_University_Microfinance_Bank => 'Olabisi Onabanjo University Microfinance Bank',
        self::Olofin_Owena_Microfinance_Bank => 'Olofin Owena Microfinance Bank',
        self::Ojokoro_Microfinance_Bank => 'Ojokoro Microfinance Bank',
        self::Oluchukwu_Microfinance_Bank => 'Oluchukwu Microfinance Bank',
        self::Otuo_Microfinance_Bank_Ltd => 'Otuo Microfinance Bank Ltd',
        self::Oraukwu_Microfinance_Bank => 'Oraukwu  Microfinance Bank',
        self::Ospoly_Microfinance_Bank => 'Ospoly Microfinance Bank',
        self::Omiye_Microfinance_Bank => 'Omiye Microfinance Bank',
        self::Oche_Microfinance_Bank  => 'Oche Microfinance Bank',
        self::Oscotech_Microfinance_Bank => 'Oscotech Microfinance Bank',
        self::Otech_Microfinance_Bank_Ltd => 'Otech Microfinance Bank Ltd',
        self::Opay => 'Opay',
        self::ProvidusBank_PLC  => 'ProvidusBank PLC',
        self::PAGE_MFBank             => 'Page MFBank',
        self::PAGE_FINANCIALS         => 'Page Financials',
        self::PAGATECH                => 'Pagatech',
        self::PARKWAY                 => 'Parkway',
        self::Parkway_Mf_Bank => 'Parkway Mf Bank',
        self::Parkway_ReadyCash => 'Parkway-ReadyCash',
        self::PAYCOM                  => 'Paycom',
        self::PALMPAY  => 'PALMPAY',
        self::Paystack_Payments_Limited => 'Paystack Payments Limited',
        self::PAYATTITUDE_ONLINE      => 'PayAttitude Online',
        self::Projects_Microfinance_Bank => 'Projects Microfinance Bank',
        self::PARRALEX                => 'Parralex',
        self::Palmcoast_Microfinance_Bank => 'Palmcoast Microfinance Bank',
        self::PARALLEX_BANK           => 'Parallex Bank',
        self::PARRALEX_MICROFINANCE_BANK => 'Parralex Microfinance bank',
        self::PatrickGold_Microfinance_Bank  => 'PatrickGold Microfinance Bank',
        self::Peace_Microfinance_Bank => 'Peace Microfinance Bank',
        self::Peniel_Micorfinance_Bank_Ltd => 'Peniel Micorfinance Bank Ltd',
        self::Personal_Trust_Microfinance_Bank=> 'Personal Trust Microfinance Bank',
        self::Pennywise_Microfinance_Bank => 'Pennywise Microfinance Bank',
        self::PecanTrust_Microfinance_Bank => 'PecanTrust Microfinance Bank',
        self::Petra_Microfinance_Bank => 'Petra Microfinance Bank',
        self::Pillar_Microfinance_Bank => 'Pillar Microfinance Bank',
        self::POLARIS_BANK            => 'Polaris Bank',
        self::Polyibadan_Microfinance_Bank => 'Polyibadan Microfinance Bank',
        self::Polyuwanna_Microfinance_Bank => 'Polyuwanna Microfinance Bank',
        self::PLATINUM_MORTGAGE_BANK  => 'Platinum Mortgage Bank',
        self::PREMIUM_TRUST_BANK      => 'PremiumTrust Bank',
        self::Prisco_Microfinance_Bank => 'Prisco  Microfinance Bank',
        self::Pristine_Divitis_Microfinance_Bank => 'Pristine Divitis Microfinance Bank',
        self::Preeminent_Microfinance_Bank => 'Preeminent Microfinance Bank',
        self::Prestige_Microfinance_Bank => 'Prestige Microfinance Bank',
        self::Purplemoney_Microfinance_Bank => 'Purplemoney Microfinance Bank',
        self::Quickfund_Microfinance_Bank => 'Quickfund Microfinance Bank',
        self::Qr_Payments => 'Qr Payments',
        self::Qube_Microfinance_Bank_Ltd => 'Qube Microfinance Bank Ltd',
        self::Radalpha_Microfinance_Bank => 'Radalpha Microfinance Bank',
        self::REFUGE_MORTGAGE_BANK    => 'Refuge Mortgage Bank',
        self::Rigo_Microfinance_Bank => 'Rigo Microfinance Bank',
        self::Rima_Microfinance_Bank => 'Rima Microfinance Bank',
        self::Resident_Fintech_Limited  => 'Resident Fintech Limited',
        self::Rehoboth_Microfinance_Bank => 'Rehoboth Microfinance Bank',
        self::Rand_merchant_Bank => 'Rand merchant Bank',
        self::Regent_Microfinance_Bank => 'Regent Microfinance Bank',
        self::RenMoney_Microfinance_Bank => 'RenMoney Microfinance Bank',
        self::Reliance_Microfinance_Bank => 'Reliance Microfinance Bank',
        self::Royal_Exchange_Microfinance_Bank => 'Royal Exchange Microfinance Bank',
        self::Rockshield_Microfinance_Bank => 'Rockshield Microfinance Bank',
        self::Rima_Growth_Pathway_Microfinance_Bank => 'Rima Growth Pathway Microfinance Bank',
        self::Richway_Microfinance_Bank => 'Richway Microfinance Bank',
        self::Rephidim_Microfinance_Bank => 'Rephidim Microfinance Bank',
        self::RAYYAN_Microfinance_Bank => 'RAYYAN Microfinance Bank',
        self::SAFETRUST  => 'SafeTrust',
        self::Safe_Haven_MFB => 'Safe Haven MFB',
        self::Safegate_Microfinance_Bank => 'Safegate Microfinance Bank',
        self::SAFETRUST_MORTGAGE_BANK => 'SafeTrust Mortgage Bank',
        self::Seed_Capital_Microfinance_Bank => 'Seed Capital Microfinance Bank',
        self::Seedvest_Microfinance_Bank => 'Seedvest Microfinance Bank',
        self::SIGNATURE_BANK => 'Signature Bank',
        self::SKYE_BANK   => 'Skye Bank Plc',
        self::Support_Mf_Bank=> 'Support Mf Bank',
        self::Shepherd_Trust_Microfinance_Bank => 'Shepherd Trust Microfinance Bank',
        self::Shongom_Microfinance_Bank_Ltd => 'Shongom Microfinance Bank Ltd',
        self::Shield_Microfinance_Bank_Ltd => 'Shield Microfinance Bank Ltd',
        self::Smartcash_Payment_Service_Bank => 'Smartcash Payment Service Bank',
        self::Sparkle   => 'Sparkle',
        self::Spay_Business => 'Spay Business',
        self::Seap_Microfinance_Bank => 'Seap Microfinance Bank',
        self::Spectrum_Microfinance_Bank => 'Spectrum Microfinance Bank',
        self::Solid_Allianze_Microfinance_Bank => 'Solid Allianze Microfinance Bank',
        self::Solidrock_Microfinance_Bank=> 'Solidrock Microfinance Bank',
        self::Supreme_Microfinance_Bank_Ltd => 'Supreme Microfinance Bank Ltd',
        self::Snow_Microfinance_Bank => 'Snow Microfinance Bank',
        self::Stanbic_IBTC_Ease_Wallet => 'Stanbic IBTC @ease wallet',
        self::STATESIDE_MFB => 'STATESIDE MFB',
        self::STANBIC_IBTC            => 'Stanbic Ibtc Bank Plc',
        self::STANBIC_MOBILE_MONEY    => 'Stanbic Mobile Money',
        self::STB_MORTGAGE_BANK       => 'Stb Mortgage Bank',
        self::STANDARD_CHARTERED_BANK => 'Standard Chartered Bank Nigeria Limited',
        self::Stanford_Microfinance_Bank => 'Stanford Microfinance Bank',
        self::Standard_Microfinance_Bank=> 'Standard Microfinance Bank',
        self::STERLING_BANK   => 'Sterling Bank Plc',
        self::Stellas_Microfinance_Bank => 'Stellas Microfinance Bank',
        self::STERLING_MOBILE         => 'Sterling Mobile',
        self::Stockcorp_Microfinance_Bank => 'Stockcorp  Microfinance Bank',
        self::SUNTRUST_BANK           => 'SunTrust Bank',
        self::SAGEGREY_FINANCE_LIMITED=> 'Sagegrey Finance Limited',
        self::Shalom_Microfinance_Bank => 'Shalom Microfinance Bank',
        self::SIMPLE_FINANCE_LIMITED  => 'Simple Finance Limited',
        self::Sagamu_Microfinance_Bank  => 'Sagamu Microfinance Bank',
        self::Sls_Mf_Bank=> 'Sls  Mf Bank',
        self::Sunbeam_Microfinance_Bank => 'Sunbeam Microfinance Bank',
        self::Sulsap_Microfinance_Bank => 'Sulsap Microfinance Bank',
        self::TAGPAY                  => 'Tagpay',
        self::Total_Trust_Microfinance_Bank => 'Total Trust Microfinance Bank',
        self::Triple_A_Microfinance_Bank => 'Triple A Microfinance Bank',
        self::Tangerine_Bank => 'Tangerine Bank',
        self::TeamApt  => 'TeamApt',
        self::TEASYMOBILE             => 'Teasy Mobile',
        self::TEKLA_FINANCE_LTD       => 'Tekla Finance Ltd',
        self::TRUSTBOND               => 'Trustbond',
        self::TANADI_MFB => 'TANADI MFB (CRUST)',
        self::TRUSTBOND_MORTGAGE_BANK => 'Trustbond Mortgage Bank',
        self::Trustfund_Microfinance_Bank => 'Trustfund Microfinance Bank',
        self::TCF_MFB                 => 'TCF MFB',
        self::Tf_Microfinance_Bank => 'Tf Microfinance Bank',
        self::TASUED_MICROFINANCE_BANK_LTD => 'TASUED MICROFINANCE BANK LTD',
        self::TEST_BANK               => 'Test bank',
        self::TITAN_TRUST_BANK        => 'Titan Trust Bank',
        self::Titan-Paystack  => 'Titan-Paystack',
        self::TAJ_BANK_LIMITED        => 'Taj Bank Limited',
        self::TAJWALLET                => 'Tajwallet',
        self::Thrive_Microfinance_Bank => 'Thrive Microfinance Bank',
        self::TRINITY_FINANCIAL_SERVICES_LIMITED => 'Trinity Financial Services Limited',
        self::Trident_Microfinance_Bank => 'Trident Microfinance Bank',
        self::UBA  => 'United Bank For Africa Plc',
        self::U_And_C_Microfinance_Bank => 'U And C Microfinance Bank',
        self::Unaab_Microfinance_Bank => 'Unaab Microfinance Bank',
        self::UNION_BANK  => 'Union Bank Of Nigeria Plc',
        self::UNITY_BANK  => 'Unity Bank Plc',
        self::Uniibadan_Microfinance_Bank => 'Uniibadan Microfinance Bank',
        self::UNN_MFB => 'UNN MFB',
        self::Ummah_Microfinance_Bank => 'Ummah Microfinance Bank',
        self::Uda_Microfinance_Bank => 'Uda Microfinance Bank',
        self::Uniben_Microfinance_Bank => 'Uniben Microfinance Bank',
        self::Umunnachi_Microfinance_Bank => 'Umunnachi Microfinance Bank',
        self::Uhuru_Microfinance_Bank=> 'Uhuru Microfinance Bank',
        self::Umuchinemere_Procredit_Microfinance_Bank => 'Umuchinemere Procredit Microfinance Bank',
        self::Uzondu_Mf_Bank => 'Uzondu Mf Bank',
        self::Unical_Microfinance_Bank => 'Unical Microfinance Bank',
        self::Uniuyo_Microfinance_Bank => 'Uniuyo Microfinance Bank',
        self::Unilag_Microfinance_Bank => 'Unilag  Microfinance Bank',
        self::Unimaid_Microfinance_Bank => 'Unimaid Microfinance Bank',
        self::Unilorin_Microfinance_Bank  => 'Unilorin Microfinance Bank',
        self::Vas2Nets_Limited => 'Vas2Nets Limited',
        self::Venture_Garden_Nigeria_Limited => 'Venture Garden Nigeria Limited',
        self::Verdant_Microfinance_Bank => 'Verdant Microfinance Bank',
        self::VTNETWORKS  => 'VTNetworks',
        self::VFD_Micro_Finance_Bank  => 'VFD Micro Finance Bank',
        self::Verite_Microfinance_Bank  => 'Verite Microfinance Bank',
        self::Visa_Microfinance_Bank=> 'Visa Microfinance Bank',
        self::Virtue_Microfinance_Bank => 'Virtue Microfinance Bank',
        self::WEMA_BANK    => 'Wema Bank Plc',
        self::WAYA_MICROFINANCE_BANK_LTD => 'WAYA MICROFINANCE BANK LTD',
        self::Wetland_Microfinance_Bank => 'Wetland Microfinance Bank',
        self::Winview_Bank  => 'Winview Bank',
        self::Woven_Finance => 'Woven Finance',
        self::Xslnce_Microfinance_Bank  => 'Xslnce Microfinance Bank',
        self::Xpress_Payments => 'Xpress Payments',
        self::Yes_Microfinance_Bank => 'Yes Microfinance Bank',
        self::Yct_Microfinance_Bank => 'Yct Microfinance Bank',
        self::Yello_Digital_Financial_Services => 'Yello Digital Financial Services',
        self::Yobe_Microfinance_Bank => 'Yobe Microfinance Bank',
        self::ZENITH_BANK             => 'Zenith Bank Plc',
        self::ZENITH_MOBILE           => 'Zenith Mobile',
        self::Zwallet => 'Zwallet',
        self::Zinternet_Nigera_Limited => 'Zinternet Nigera Limited',
        self::Zikora_Microfinance_Bank => 'Zikora Microfinance Bank',
        self::3Line_Card_Management_Limited  => '3Line Card Management Limited',
        self::9Payment_Service_Bank => '9 Payment Service Bank',
    ];

    /**
     * Returns an associative array containing of bank codes in the form: [code => bank_name].
     *
     * @return array
     */
    public static function getBanks(): array
    {
        return self::BANK_CODES;
    }

    /**
     * Returns an associative array containing of bank codes in the form: [code => bank_name].
     *
     * @return array
     */
    public static function getSupportedBanks(): array
    {
        return array_merge(
            [self::ACCESS_BANK => self::BANK_CODES[self::ACCESS_BANK]],
            self::getSupportedBanksForInternetBanking()
        );
    }

    /**
     * Returns the list of support banks for internet banking billing.
     *
     * @return array
     */
    public static function getSupportedBanksForInternetBanking(): array
    {
        $codes = [self::GTBANK, self::UBA, self::DIAMOND_BANK, self::ZENITH_BANK, self::FIRST_BANK];
        // the supported banks for internet banking
        return array_filter(self::BANK_CODES, function ($key) use ($codes) {
            return in_array($key, $codes);
        }, ARRAY_FILTER_USE_KEY);
    }
}


